name: domain
publish_to: "none"

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies: 
  fimber: 0.6.4
  latlng: 0.1.0
  injectable: ^1.5.0
  get_it: ^7.2.0

dev_dependencies:
  build_runner: ^2.1.5
  injectable_generator: ^1.5.2